# What's in this notebook?
* The purpose of this notebook is to merge all of our data sets of interest on the 'Quarter' variable then export them as a final data set with M-score (~1977 - 2013) and one without M-score (~1976 - 2023)
* Before merging I will drop the 'Date' column for all quarters.
* At the end datasets will be different sizes but should not contain NaN values.

In [44]:
# Most if not all imports
import pandas as pd
import numpy as np

In [45]:
# Dow Jones Industrial:
indu = pd.read_csv(r"C:\Users\Edmund\OMSA\MGT6203\group project\Team36_group_project\Data\clean_INDU_data202310308286.csv")
# S&P 500:
sp500 = pd.read_csv(r"C:\Users\Edmund\OMSA\MGT6203\group project\Team36_group_project\Data\clean_index_data202310251597.csv")
# Weighted average beta:
wab = pd.read_csv(r"C:\Users\Edmund\OMSA\MGT6203\group project\Team36_group_project\Data\MCAP_WAB20231031123947.csv")
# Real GDP, PPI, Yield curve:
macro = pd.read_csv(r"C:\Users\Edmund\OMSA\MGT6203\group project\Team36_group_project\Data\GDP_PPI_YC_20231025203618.csv")
# M-Score:
m_score = pd.read_csv(r"C:\Users\Edmund\OMSA\MGT6203\group project\Team36_group_project\Data\final_M.csv")

In [46]:
# First lets examine the heads and tails of each dataframe:
print('### Dow Jones Industrial ###')
# display(indu.head())
# display(indu.tail())
print("First and last quarter in indu: {} , {}".format(indu['Quarter'].iloc[0], indu['Quarter'].iloc[-1]))
print("Number of NaN values in indu: {}".format(np.count_nonzero(indu.isnull())))

print('### S&P 500 ###')
print("First and last quarter in sp500: {} , {}".format(sp500['Quarter'].iloc[0], sp500['Quarter'].iloc[-1]))
print("Number of NaN values in sp500: {}".format(np.count_nonzero(sp500.isnull())))

print('### Weighted average beta and MCAP ###')
print("First and last quarter in WAB: {} , {}".format(wab['Quarter'].iloc[0], wab['Quarter'].iloc[-1]))
print("Number of NaN values in WAB: {}".format(np.count_nonzero(wab.isnull())))

print('### Macroeconomic data ###')
print("First and last quarter in macro: {} , {}".format(macro['Quarter'].iloc[0], macro['Quarter'].iloc[-1]))
print("Number of NaN values in macro: {}".format(np.count_nonzero(macro.isnull())))

print('### M-score ###')
print("First and last quarter in M-score: {} , {}".format(m_score['Quarter'].iloc[0], m_score['Quarter'].iloc[-1]))
print("Number of NaN values in M-score: {}".format(np.count_nonzero(m_score.isnull())))
display(m_score[m_score.isnull().any(axis=1)]) # print any row where index is na
# in m_score all NaN values are in first row. I will start with 1977Q2 anyway, because earlier quarters have small samples sizes.

# Date range with M-score and WAB:  1977Q2 - 2013Q2
# Date range without M-score and WAB: 1976Q3 - 2023Q1


display(m_score.head())
display(m_score.tail())
display(wab.head())

### Dow Jones Industrial ###
First and last quarter in indu: 1975Q1 , 2023Q2
Number of NaN values in indu: 0
### S&P 500 ###
First and last quarter in sp500: 1975Q1 , 2023Q2
Number of NaN values in sp500: 0
### Weighted average beta and MCAP ###
First and last quarter in WAB: 1975Q2 , 2019Q3
Number of NaN values in WAB: 0
### Macroeconomic data ###
First and last quarter in macro: 1976Q3 , 2023Q1
Number of NaN values in macro: 0
### M-score ###
First and last quarter in M-score: nan , 2013Q2
Number of NaN values in M-score: 2

  Quarter Avg. M-Score Weighted_M  Count
0     NaN         mean        sum    NaN

  Quarter         Avg. M-Score           Weighted_M  Count
0     NaN                 mean                  sum    NaN
1  1976Q4  -3.4074183669427094  -3.2035868693934204    3.0
2  1977Q1  -2.7752430354784208   -2.296566837018445    7.0
3  1977Q2   -2.928934632691999  -3.5874774628369273   54.0
4  1977Q3   -2.892064025263317  -3.6027085118950226   58.0

    Quarter         Avg. M-Score           Weighted_M  Count
143  2012Q2   -2.362824406088347   -2.728989947892826  324.0
144  2012Q3  -2.3864508194628278  -2.8061368602163514  314.0
145  2012Q4  -2.3931727750762724  -2.8817427730094134  315.0
146  2013Q1   -2.227828103540768  -2.5051883936430634  309.0
147  2013Q2  -2.3858815872810104   -2.650669318580677  308.0

,date,average beta,average MCAP,WAB,average beta trend,average MCAP trend,WAB trend,average beta velocity,average beta acceleration,average MCAP velocity,average MCAP acceleration,WAB velocity,WAB acceleration,Quarter
0,1975-06-30,0.610682,144714.907194,0.000193,0.614285,139490.324442,0.000192,0.001896,0.002573,-684.540091,-3958.991073,-1.077683e-06,2.090114e-08,1975Q2
1,1975-09-30,0.616208,126640.135252,0.000191,0.613179,129419.777670,0.000191,-0.007076,-0.001518,-356.550697,2646.856665,-1.744760e-07,2.549849e-08,1975Q3
2,1975-12-31,0.610191,132300.399802,0.000190,0.615644,138072.828638,0.000191,0.014366,0.003730,5290.585639,1105.322863,6.768475e-07,7.100104e-08,1975Q4
3,1976-03-31,0.638686,154190.862270,0.000193,0.642219,151537.518612,0.000191,-0.000615,-0.003714,874.394074,-2136.524608,-6.577210e-07,-2.563274e-07,1976Q1
4,1976-06-30,0.632326,153426.689636,0.000189,0.633752,152836.017684,0.000189,-0.003995,-0.000756,2350.730567,802.794687,1.197445e-06,7.899563e-07,1976Q2

In [47]:
# Date range with M-score and WAB:  1977Q2 - 2013Q2
# Date range without M-score and WAB: 1976Q3 - 2023Q1

# 1) First make 2 merges (one with WAB and M-score and one without)
# 2) Sort each frame by Quarter:  DataFrame.sort_values(by, *, axis=0, ascending=True....
# 3) find the Quarters of interest then select just those rows
# 4) check for NaN values.
# 5) Export 2 final dataframes to csv.
merge_large = sp500.drop('DATE', axis=1).merge(indu.drop('DATE', axis=1),
                                                on = 'Quarter', how = 'left') # left merge drop date column
merge_large = merge_large.merge(macro.drop('DATE', axis=1),
                                                on = 'Quarter', how = 'left') # left merge drop date column
merge_large = merge_large.dropna()

merge_large.sort_values(by ='Quarter', ascending = True, inplace = True) # sort values by quarterly date

# now let's create the small dataset by merging in m_score and wab
# first only get data for dates >= 1977Q2 (where company sample size is large)
m_score_min_idx = m_score.index[m_score['Quarter'] == '1977Q2']
print('m_score_min_idx:')
print(m_score_min_idx[0])
ms_trim = m_score.iloc[m_score_min_idx[0]:,:]

merge_small = ms_trim.merge(merge_large, on = 'Quarter', how = 'left') # this left merge should elimiate dates after 2013
merge_small = merge_small.merge(wab.drop('date', axis=1), on = 'Quarter', how = 'left')
merge_small = merge_small.dropna()
merge_small.sort_values(by ='Quarter', ascending = True, inplace = True) # sort values by quarterly date

# # now let's trim the dates
# large_start_idx = merge_large.index[merge_large['Quarter'] == '1977Q2']
# large_end_idx = merge_large.index[merge_large['Quarter'] == '2013Q2']

# now let's look at the heads and tails:
display(merge_large.head())
display(merge_large.tail())

display(merge_small.head())
display(merge_small.tail())

# before we add m-score we should trim m-score dates and convert numeric columns to float: (formating was messed up by extra header row)
	

print(merge_small.columns)


# def select_small_date_range(df): # Select dates between 1977Q2 and 2013Q2
#     start_idx = df.index[df['Quarter'] == '1977Q2']
#     end_idx = df.index[df['Quarter'] == '1977Q2']

# def select_big_date_range(df): # Select dates between 1976Q3 and 2023Q1

# print(type(sp500['Quarter'].iloc[4])) # so these dates come in as strings
# print(type(m_score['Avg. M-Score'].iloc[4]))
# print(type(sp500['sp500 return'].iloc[4]))
# print(type(indu['indu return trend'].iloc[4]))
# print(type(m_score['Weighted_M'].iloc[4]))
# print(type(m_score['Quarter'].iloc[4]))
# print(type(m_score['Count'].iloc[4]))
# print(type(indu['Quarter'].iloc[4]))

# # It seems that 'Quarter' columns are type str and all M-score columns except 'Count' are str.
# # first I'll convert Avg. M-Score and Weighted_M from str to float.
# m_score['Avg. M-Score'] = m_score['Avg. M-Score'].astype(float)
# print(type(m_score['Avg. M-Score'].iloc[4]))

m_score_min_idx:
3

,sp500 return,sp500 return trend,sp500 velocity,sp500 acceleration,Quarter,indu return,indu return trend,indu velocity,indu acceleration,GDPC1,WPSID62,WPSID62 trend,WPSID62 velocity,WPSID62 acceleration,T10Y2Y,T10Y2Y trend,T10Y2Y velocity,T10Y2Y acceleration
6,-0.001234,0.000012,0.000101,-0.000026,1976Q3,0.008929,-0.000165,0.000116,-0.000029,6012.356,63.4,63.333333,-0.30,0.350,1.22,1.289292,0.004792,-0.000260
7,0.005427,0.000090,-0.000076,-0.000062,1976Q4,0.017706,0.000179,-0.000052,-0.000025,6083.391,64.5,64.066667,0.45,-0.075,1.47,1.399542,0.001042,-0.000167
8,-0.001218,-0.000570,0.000076,0.000005,1977Q1,0.009097,-0.000502,0.000065,-0.000006,6201.659,66.6,66.866667,1.30,-0.325,1.41,1.292667,-0.002250,0.000115
9,0.003696,0.000019,-0.000013,-0.000050,1977Q2,0.015745,-0.000424,-0.000023,-0.000057,6313.559,65.5,65.933333,-1.45,0.300,1.12,1.036417,-0.007271,0.000135
10,0.007094,-0.000471,-0.000031,-0.000099,1977Q3,0.021129,-0.000702,-0.000023,-0.000107,6313.697,63.7,63.866667,0.05,0.675,0.59,0.627292,-0.005333,0.000406

,sp500 return,sp500 return trend,sp500 velocity,sp500 acceleration,Quarter,indu return,indu return trend,indu velocity,indu acceleration,GDPC1,WPSID62,WPSID62 trend,WPSID62 velocity,WPSID62 acceleration,T10Y2Y,T10Y2Y trend,T10Y2Y velocity,T10Y2Y acceleration
188,-0.015653,-0.000498,0.000056,-0.000018,2022Q1,-0.015625,-0.000262,0.000024,-0.000003,19895.271,307.361,310.882000,12.6185,0.50400,0.04,0.348958,-0.006562,-0.000323
189,-0.008759,-0.000654,0.000072,-0.000046,2022Q2,-0.008071,-0.000549,0.000046,-0.000048,20054.663,359.299,343.255000,-7.6480,-12.49950,0.06,-0.026000,-0.003292,0.000198
190,-0.015067,0.000084,-0.000322,-0.000017,2022Q3,-0.017112,0.000798,-0.000225,-0.000021,20182.491,332.763,325.579667,-21.3510,-11.63575,-0.39,-0.428292,-0.003896,-0.000281
191,-0.002541,0.000489,-0.000073,0.000015,2022Q4,-0.002214,0.000488,-0.000148,-0.000018,20282.760,295.882,289.771333,-4.6820,-5.70850,-0.53,-0.631417,-0.000562,-0.000167
192,0.014437,0.000686,-0.000071,-0.000007,2023Q1,0.012633,0.000043,-0.000044,0.000015,20386.467,255.668,260.789333,-4.9430,3.86400,-0.58,-0.673250,-0.002458,0.000240

,Quarter,Avg. M-Score,Weighted_M,Count,sp500 return,sp500 return trend,sp500 velocity,sp500 acceleration,indu return,indu return trend,...,WAB,average beta trend,average MCAP trend,WAB trend,average beta velocity,average beta acceleration,average MCAP velocity,average MCAP acceleration,WAB velocity,WAB acceleration
0,1977Q2,-2.928934632691999,-3.5874774628369273,54.0,0.003696,0.000019,-0.000013,-5.000753e-05,0.015745,-0.000424,...,0.000188,0.588399,156646.124973,0.000188,-0.001597,0.000169,1596.925166,-1140.399834,4.257808e-07,-3.720542e-07
1,1977Q3,-2.892064025263317,-3.6027085118950226,58.0,0.007094,-0.000471,-0.000031,-9.916646e-05,0.021129,-0.000702,...,0.000188,0.588532,154317.129999,0.000188,0.006019,0.004604,-1099.740210,1090.703081,4.579012e-07,3.254375e-07
2,1977Q4,-2.905239586144571,-3.580334425014138,58.0,0.001685,-0.000529,-0.000044,-1.726593e-05,0.016896,-0.000693,...,0.000191,0.619210,155068.429908,0.000190,0.006875,-0.004539,-1426.625694,-1090.236012,2.057119e-07,-4.117815e-07
3,1978Q1,-2.762484806421322,-3.3937682706920973,58.0,-0.002237,0.001173,0.000151,-4.456153e-07,0.011703,0.001397,...,0.000191,0.611632,156117.118476,0.000192,-0.010227,-0.000748,6049.221168,2017.425039,1.685134e-06,3.986992e-07
4,1978Q2,-2.857087241075664,-3.3762760893477486,58.0,-0.000419,0.000882,0.000099,-5.849000e-06,0.010869,0.000848,...,0.000195,0.598109,172566.120580,0.000195,0.000685,0.002822,4570.248510,78.710149,-1.510248e-07,-7.294480e-07

,Quarter,Avg. M-Score,Weighted_M,Count,sp500 return,sp500 return trend,sp500 velocity,sp500 acceleration,indu return,indu return trend,...,WAB,average beta trend,average MCAP trend,WAB trend,average beta velocity,average beta acceleration,average MCAP velocity,average MCAP acceleration,WAB velocity,WAB acceleration
140,2012Q2,-2.362824406088347,-2.728989947892826,324.0,0.024920,0.000123,-0.000077,0.000064,0.022046,0.000084,...,0.000173,0.917943,9.471887e+05,0.000172,-0.004853,-0.000043,1606.447320,9718.738794,-4.478629e-07,6.089730e-07
141,2012Q3,-2.3864508194628278,-2.8061368602163514,314.0,-0.004478,0.000506,-0.000131,-0.000041,-0.003622,0.000330,...,0.000173,0.904405,9.830195e+05,0.000173,-0.005110,-0.001098,10719.534442,-2766.701385,-3.089023e-07,-4.737745e-07
142,2012Q4,-2.3931727750762724,-2.8817427730094134,315.0,0.016942,0.000925,0.000113,-0.000017,0.012833,0.001029,...,0.000170,0.886904,1.010914e+06,0.000171,-0.004428,0.000885,16002.119245,4801.819074,-2.535398e-07,3.585733e-07
143,2013Q1,-2.227828103540768,-2.5051883936430634,309.0,0.004057,0.001033,-0.000043,0.000010,0.003606,0.001236,...,0.000170,0.879893,1.063274e+06,0.000171,0.001603,0.001843,12686.678802,-4989.349887,6.866770e-07,-1.711594e-08
144,2013Q2,-2.3858815872810104,-2.650669318580677,308.0,-0.004290,0.000402,0.000020,0.000040,-0.007647,0.000235,...,0.000170,0.881840,1.089688e+06,0.000171,-0.000885,0.000862,7416.344081,648.873358,-6.509373e-07,1.490780e-07

Index(['Quarter', 'Avg. M-Score', 'Weighted_M', 'Count', 'sp500 return',
       'sp500 return trend', 'sp500 velocity', 'sp500 acceleration',
       'indu return', 'indu return trend', 'indu velocity',
       'indu acceleration', 'GDPC1', 'WPSID62', 'WPSID62 trend',
       'WPSID62 velocity', 'WPSID62 acceleration', 'T10Y2Y', 'T10Y2Y trend',
       'T10Y2Y velocity', 'T10Y2Y acceleration', 'average beta',
       'average MCAP', 'WAB', 'average beta trend', 'average MCAP trend',
       'WAB trend', 'average beta velocity', 'average beta acceleration',
       'average MCAP velocity', 'average MCAP acceleration', 'WAB velocity',
       'WAB acceleration'],
      dtype='object')

In [49]:
# Now check for NaN and check shapes of dataframes then export them to csv. Model building comes next.
print('### Check size of small dataset and check for NaN values ###')
print("merge_small shape: {} ".format(merge_small.shape))
print("Number of NaN values in merge_small: {}".format(np.count_nonzero(merge_small.isnull())))

print('### Check size of large dataset and check for NaN values ###')
print("merge_large shape: {} ".format(merge_large.shape))
print("Number of NaN values in merge_large: {}".format(np.count_nonzero(merge_large.isnull())))

### Check size of small dataset and check for NaN values ###
merge_small shape: (145, 33)
Number of NaN values in merge_small: 0
### Check size of large dataset and check for NaN values ###
merge_large shape: (187, 18)
Number of NaN values in merge_large: 0

In [50]:
# Ok. Time to export both of these to csv:
from datetime import datetime
now = datetime.now()
date_str = str(now.year) + str(now.month) + str(now.day) + str(now.hour) + str(now.minute) + str(now.second)
#print(date_str)
output_dir = r"C:\\Users\\Edmund\\OMSA\\MGT6203\\group project\Team36_group_project\Data\\"
fname1 = output_dir + "merged_data"  + date_str + '.csv'
merge_large.to_csv(fname1, index=False)
fname2 = output_dir + "merged_data_mscore_wab"  + date_str + '.csv'
merge_small.to_csv(fname2, index=False)